language: python

dist: xenial

stages:
  - linting

python:
  - "3.7"

cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"  

install:
  - pip install -r requirements-dev.txt

script:
  - pre-commit run --all-files