language: python
cache: pip
python:
    - 3.6
matrix:
    allow_failures:
        - python: nightly
        - python: pypy
        - python: pypy3
install:
    - pip install flake8
before_script:
    - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
script:
    - true
notifications:
    on_success: change
    on_failure: change
