version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.5
    environment:
      POETRY_VERSION: 1.0.0b9
    steps:
      - checkout
      - run:
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run:
          name: Setup
          command: |
            sudo pip install poetry==${POETRY_VERSION}
            sudo pip install pre-commit
            mkdir -p /home/circleci/.config/pypoetry/
            echo "[repositories]" > /home/circleci/.config/pypoetry/config.toml
            poetry config virtualenvs.create false
            pre-commit install-hooks
      - run:
          name: Lint
          command: pre-commit run --all-files
      - run:
          name: Build
          command: |
            poetry build
      - store_artifacts:
          path: dist
